[workspace]
resolver = "2"
members = [
    "core",
    "graphics",
    "demos",
]

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "MIT"
repository = "https://github.com/IvanPleshkov/RedLilium"

[workspace.dependencies]
# Window and input handling
winit = "0.30.12"

# Logging
log = "0.4"
env_logger = "0.11"

# Web support
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
web-sys = "0.3"
console_log = "1.0"
console_error_panic_hook = "0.1"
