[package]
name = "redlilium-vfs"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Virtual file system for RedLilium Engine"

[features]
default = ["filesystem"]
filesystem = []

[dependencies]
log.workspace = true
