[book]
title = "RedLilium Engine"
authors = ["Ivan Pleshkov"]
language = "en"
src = "src"

[build]
build-dir = "book"

[output.html]
default-theme = "navy"
preferred-dark-theme = "navy"
git-repository-url = "https://github.com/IvanPleshkov/RedLilium"
